# Generated by Django 4.1 on 2022-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="Attachment",
            field=models.FileField(
                default="settings.MEDIA_ROOT/media/test.txt", upload_to="media"
            ),
        ),
    ]
